### ISSUE TITLE
How to flash foxbms firmware to MCU?

### ISSUE THREAD

**Issue by huyleincepit** [foxBMS/foxbms-2#12]
Hi, foxbms2 developing team,

Can you help me to flash the firmware to MCU?
I have built the foxbms-2 [rev:  9eb6d1c] by using command: 
`C:\huyle\projects\TSME\foxBMS\foxbms-2> waf build_bin` 

Then, the program has been built successfully, there are files: **foxbms.bin, foxbms.elf, and foxbms.hex** in **foxbms-2\build\bin\src\app\main\** directory

I have a dev kit: TMDX570LC43HDK [(ti.com/tool/TMDX570LC43HDK)](https://www.ti.com/tool/TMDX570LC43HDK) connecting to my PC at COM14 port. 
I have tried flashing the foxbms-2 firmware to devkit by command:
`C:\huyle\projects\TSME\foxBMS\foxbms-2> waf install_bin`
But, it has appeared some error: 

```
Build failed
Traceback (most recent call last):
  File "C:\huyle\projects\TSME\foxBMS\foxbms-2\tools\waf3-2.0.22-1241519b19b496207abef1f72bbf61c2\waflib\Task.py", line 180, in process
    ret=self.run()
  File "C:\huyle\projects\TSME\foxBMS\foxbms-2\tools\waf-tools\f_j_flash.py", line 200, in run
    self.generator.bld.fatal("No debugger configured in the flash tool.")
  File "C:\huyle\projects\TSME\foxBMS\foxbms-2\tools\waf3-2.0.22-1241519b19b496207abef1f72bbf61c2\waflib\Context.py", line 261, in fatal
    raise self.errors.ConfigurationError(msg,ex=ex)
waflib.Errors.ConfigurationError: No debugger configured in the flash tool.
```
I have read docs of forbms-2 [(docs.foxbms.org)](https://docs.foxbms.org/) but cannot find the specified guideline which tell "how to flash".

Please help me to flash the firmware, 
Thank you

**Comment by foxBMS** [comment]
Dear @huyleincepit ,

Flashing the MCU requires a debugger (currently Lauterbach is known to be working best, see the foxBMS 2 documentation on [Lauterbach](https://docs.foxbms.org/tools/debugger/debugger-lauterbach.html)) and **most important a foxBMS 2 hardware** (see https://github.com/foxBMS/foxbms-2/tree/master/hardware).

As IOs etc. are set in the sources specifically to the foxBMS 2 master hardware, flashing and running this binary on other hardware than foxBMS 2 BMS Master will **not** result in the expected behavior and **might even damage** the hardware you are flashing the binary onto.

Best regards,
The foxBMS Team
