### ISSUE TITLE
Programming of PMIC/SBC for foxBMS-2 Master card

### ISSUE THREAD

**Issue by BhavaySen** [foxBMS/foxbms-2#20]
Hello, 
Please share  the programming procedure for MC33FS8530A0ES used in master card. Is foxBMS firmware module have the code in it? or as per the information we have to program it before assembly. Please share the procedure or share the section where it is mentioned in the documentation. As you cannot share the OTP because of NDA.

Best Regards,
Bhavay Sen

------------------------------------------------------------------
Adding Previous conversation,

@BhavaySen 
Hello Team foxBMS,

One part MC33FS830A0ES is used in MASTER Card. This is an OTP IC, I have not gone through all the modules of firmware yet but wanted to know that the programming of this IC is done in the firmware or is it already programmed before assembly??
This A0 part of ASIL D category is used in two different flavor. Program to set the desired configuration is covered in firmware in documentation???

@foxBMS
Owner
[foxBMS](https://github.com/foxBMS) commented [18 hours ago](https://github.com/foxBMS/foxbms-2/issues/13#issuecomment-1689688343)
Dear @BhavaySen,

The MC33FS830A0ES needs to be programmed before the PCB is assembled. The details of the MC33FS830A0ES one-time programming cannot be shared due to NDAs.

For future questions, bug reports and similar, please open each time a specific issue.

Best regards,
The foxBMS Team

**Comment by foxBMS** [comment]
Dear @BhavaySen,

- The MC33FS830A0ES needs to be programmed before the PCB is assembled.
- The different voltages the MC33FS830A0ES needs to supply can be seen on the schematics.
- The details of **how to program** these voltages in the MC33FS830A0ES cannot be shared due to NDAs. You need to get in contact with the manufacturer yourself to get this information.

Best regards,
The foxBMS Team
