### ISSUE TITLE
Wrong link to F900 fuse in BOM for LTC6811 slave

### ISSUE THREAD

**Issue by luiginoschese** [foxBMS/foxbms-2#32]
Wrong link to F900 fuse in columns H and J of BOM for LTC6811 slaves. Links point to 0.125A fuse instead of 1.25A fuse.

**Comment by foxBMS** [comment]
Dear @luiginoschese,

thanks for the report, we will have a look.

Best regards,
The foxBMS Team

**Comment by foxBMS** [comment]
Dear @luiginoschese,

We have updated the release for the LTC LTC6811-1 based BMS-Slave (see <https://iisb-foxbms.iisb.fraunhofer.de/foxbms/gen2/hardware/release/slave-12-ltc-ltc6811-1-v2.1.7.zip>).

Please note:

- the Farnell number was and still is correct in the previous release and also in the library. Only the link to Octopart was wrong. This has been fixed in the Excel sheet.
- this is a quick release, i.e., it fixes the Excel, but the library (where the information is actually stored) is still not correct. As the LTC LTC6811-1 based BMS-Slave is no longer developed, there is **no** new Altium released planned that fixes the library and bumps the version number. This means, if you run a new Altium release job to generate the BOM etc., you have to again fix the Excel sheet manually. If you require a new release (i.e., that would be v2.1.8) that includes the full fix, please contact us at [info@foxbms.org](mailto:info@foxbms.org).

Best regards,
The foxBMS Team
